fix: convert milliseconds to seconds for storing in redis
node-cache-manager/node-cache-manager-ioredis-yet pull request #65
Opened 2022-12-14 09:29 UTC by iangregsondev

The set was not being converted to seconds, so using it from cache-manager and passing in milliseconds would store in redis for a very long time.

The mset seems to have already added this.

2022-12-16 02:48 UTC, wangkunmeng approved these changes

2022-12-21 18:28 UTC, botika approved these changes

2022-12-21 18:30 UTC, botika requested changes
CI fails

2022-12-21 18:33 UTC, iangregsondev commented
I thought there was an update here https://github.com/node-cache-manager/node-cache-manager-ioredis-yet/issues/66

By @wangkunmeng

2022-12-21 18:33 UTC, iangregsondev commented
Not sure if he made a PR though.

lost :-)

2022-12-21 20:32 UTC, closed without merging